# Hugo variables
baseURL = "http://localhost"
languageCode = "en-us"
title = "Karsten's blog"
theme = "bootstrap4-blog"
enableRobotsTXT = true
pygmentsCodefences = true
pygmentsStyle = "pygments"
paginate = 3
copyright = "Except otherwise noted, content on this site is licensed under a <a rel='license' target='_parent' href='https://creativecommons.org/licenses/by-sa/4.0/'>Creative Commons Attribution 4.0 International license</a>."
enableGitInfo = true
enableEmoji = true

[permalinks]
  posts = "/:year/:month/:slug/"
  page = "/:slug/"

[[menu.navbar]]
  name = "Github"
  url = "https://github.com/karstenmueller"

[[menu.navbar]]
  name = "Linkedin"
  url = "https://www.linkedin.com/in/karmueller/"

[params]
  author = "Karsten Müller"
  # description = "Description/Subtitle"
  date_format = "2006-01-02"
  # google_verify_meta = ""
  sharingicons = false
  cookie_consent_info_url = "http://cookiesandyou.com"
  
  [params.social]
    # twitter handle for the site
    twitter = "karstenmueller"

  [params.sidebar]
    # Optional about block for sidebar (can be Markdown)
    about = "Enjoy my ramblings and musings <p>[About me →](/about)"

DefaultContentLanguage = "en"
